sudo: required
services:
  - docker

before_install:
  - docker image build -t sumeetpri/docker-react -f Dockerfile.dev .

  script:
    - docker container run sumeetpri/docker-react npm run test -- --coverage
