sudo: required
services:
  - docker
before_install:
  - docker image build -t sumeetpri/docker-react -f Dockerfile.dev .

script:
  - docker container run e CI=true sumeetpri/docker-react npm run test -- --coverage